"""Measured R2 tables and setup cards only after the corresponding fixed gate."""
from __future__ import annotations

import json

from .sources import EVIDENCE, ROOT


def f(value,n=2):
    return 'NA' if value is None else f'{value:.{n}f}'


def main(stage='DEVELOPMENT'):
    result=json.loads((EVIDENCE/f'{stage}_RESULTS.json').read_text())
    manifest=json.loads((EVIDENCE/f'SOURCE_MANIFEST_{stage}.json').read_text())
    roster=json.loads((EVIDENCE/'FROZEN_R2_ROSTER.json').read_text())
    by={(x['candidate'],x['cost_case']):x for x in result['rows']}
    ids=[x['id'] for x in roster['candidates'] if (x['id'],'STRESS') in by]
    out=[f'# BTC flow/regime multi-season measured strategy discovery R2 — {stage}', '',
        f"**Terminal: `{result['terminal']}`. Development promotions: {result['promoted_ids']}. Validation-pass IDs: {result['validation_pass_ids']}.**", '',
        'This is the result of the fixed finite campaign, not a universal claim about BTC opportunities. No hypothesis card is published without its corresponding gate. Low-count positive episodes are disclosed with support failures.', '',
        '## Identity and access chronology', '',
        f"Task `{roster['task_id']}`. Controller `{roster['controller_dispatch_sha']}`; Prompt `{roster['prompt_sha']}`. Exact code parent `{roster['exact_start_sha']}`; outcome-blind freeze `{result['freeze_sha']}`. All four original freeze files stay byte-identical to the first commit, which was pushed and remotely verified before development source access. Final parent chain and exact remote SHA are returned with the push; the frozen design is not rewritten after outcomes.", '',
        f"First actual {stage} CSV body read: `{manifest['first_price_csv_read_at_utc']}`; source download stage started `{manifest['started_at_utc']}`. Source manifest SHA256 `{result['source_manifest_sha256']}`. Root requested Codex GPT-6 Sol High, actual root model/effort NOT_EXPOSED. Bounded source/signal implementation workers have observable GPT-6 Sol Medium tool roles; their inputs were synthetic, and the parent froze the economic experiment and executed actual data.", '',
        'Development is 2021–2023 Feb/Jun/Sep/Dec with Jan/May/Aug/Nov warmup; validation is separately reserved new months2024–2025. Exposed R1 Aprils mean whole years are not pristine OOS. No R2 validation ZIP download, stat or body read occurs for DEVELOPMENT_NO_GO. No source selection, retuning, alternative months or additional strategy search follows this measured rejection.', '',
        '## Actual source and measurement grade', '',
        f"{len(manifest['records'])} selected official Binance Vision USD-M BTCUSDT perpetual 1m monthly archives, {sum(r.get('price_rows',0) for r in manifest['records']):,} rows, {len(manifest['complete_folds'])} full scored folds, years {manifest['complete_years']}. All admitted months have provider SHA256 match, one exact declared CSV member, actual positional/header12-column schema, millisecond UTC calendar/open+59,999ms close, dense60s cadence, no duplicates/gaps/deletions. Every current ZIP was reparsed with the strict final Decimal `0<=taker_buy_base<=base_volume` check before signal computation, and matched its recorded CSV/cache hash. No taker volume was clamped or imputed; the original downloader observed zero tiny-bound excursions. Missing/non-PIT quantities do not get filled from future data.", '',
        'The actual taker-buy field is CSV zero-based9, BTC base units; base traded volume is field5. Summed buyer-initiated base volume / summed total base volume gives I=2B/V−1 on closed15m/1h/4h groups. This is an aggression/activity proxy, not observed liquidation, OI, orderbook depth, maker liquidity or informed flow. Zero volume makes I undefined and required flow rules WAIT. Current archive snapshots may contain publisher corrections; end+60s availability is a reconstruction assumption, not proof of historical publication/known-at.', '',
        'Scores exclude first and last UTC day of each month. Entry plus maximum horizon plus ACK must fit score end; all live position paths remain inside the selected score month, warmup is never scored. Only the selected adjacent warmup seeds indicators, with minimum60completed4h bars. No earlier undeclared candles or 2026, protected Forward/H39-H41/A-line outcome, owner Quant-agent/data (including stat), original account or private exchange API was accessed.', '',
        'Provider: [Binance public data](https://github.com/binance/binance-public-data). [Dataset terms v1.0 dated2026-08-26](https://github.com/binance/binance-public-data/blob/master/TERMS_AND_CONDITIONS.md) were checked and frozen: these derived analytical artifacts carry Binance Vision attribution and CC BY-NC-SA4.0 for noncommercial personal nonproduction research. Raw ZIP/CSV/cache and complete trade/market/account paths stay in task-owned /tmp outside Git; no commercial signal-sale or live-trading rights follow. Generic code is not a relicensing of market data.', '',
        '## Distinct hypotheses and fixed economics', '',
        'The six new bidirectional families are separate economic mechanisms, not a reranking of R1 losers: flow-confirmed trend acceptance8h; price/flow exhaustion4h; low-efficiency range reentry4h; prior compressed volatility with next-quarter release acceptance12h; repeated rejection against opposite aggressor pressure8h; two-hour pressure persistence with bounded new-hour continuation24h. Every exact inequality, tail/channel definition, RSI Wilder seed, arithmeticATR20, EMA20/50 seed and ER12 is in FROZEN_R2_ROSTER.json. No weights, thresholds, stop multipliers, direction or hold were fitted to this data.', '',
        'Why R1 did not promote: original12h cost geometry exceeded its fixed250bp stop cap; structural/retest had very little or no support; the old contained impulse/compression24h conjunction had zero signals; generic price-only8h gross moves did not consistently cover22/44bp. Those R1 outcomes are exposed and remain unedited. R2 tests different pressure/regime counterparties, not a post-hoc tweak to R1 thresholds. Each is only a hypothesis that the counterparties could pay a gross move larger than44bp; the measured table supplies the test.', '',
        'Unmodified R1 standalone simulate/episode is reused. Signal exclusiveend→decision+60s→entry+120s; actualnextopen gap veto=.25hourATR. Registered initial structural/ATR stops, 30..300bp raw risk, fixed2R effective-entry target, stop-first same-minute collision, adverse stop gaps at worse open, favorable target gaps capped. Each candidate/cost/month is an independent1000USDT cash book,50% allocation before5%reserve, no leverage multiplier or cross-candidate pooling. R1 conservative sizing reserves entry,1.10 exit-cost and1.10 unknown-hourlyFunding; reserving is not inventing a settled bill. R1 causal100USDT drawdown disable uses the last available(i−2)trade-price proxy and queues next-open action; the new acceptance gate is max close+MTM DD<=15%, not a changed engine threshold. Cooldown and ACK stay frozen.', '',
        'BASE22bp =eachleg6fee+2spread+3slip; STRESS44bp =12+4+6. Fee is charged once on each actual executed notional, spread/slip embedded once with conservative .1USDT tick rounding. Targets are2R from each case actual effective entry, so a changed cost case can change raw exit timing, later cooldown and gross returns; sensitivity is a replay, not merely subtracting22bp from the same exits. Lot .001BTC/minnotional5USDT/fee tiers/latency/spread/slip are assumed proxies, not independently verified historical Binance filters or achieved economics. Unknown actual signedFunding is never credited or included in main net cash; true Mark and source known-at remain UNKNOWN. Class EXPLORATORY_COST_PROXY_ONLY; no Alpha, effectiveP3/P4/testnet/live/funds authority.', '',
        'Important return identity: a trade netbp uses initial raw entry notional; netR uses fixed effective initial risk; account return is netcash/1000 within one monthly book. Per-year cash statistic averages four independent monthly1000 books, not a continuously funded annual return or leverage-on-margin result. SumUSDT over different reset books is labelled separately and never presented as return on a single1000. Dense trade-price MTM includes liquidation-cost proxy each minute; closeDD only trade settlements. MAE/MFE envelopes include full touched minute extrema, potentially after exit within that minute, and are not asserted path timing.', '',
        '## All fixed candidates, BASE and STRESS', '',
        '| Candidate | Cap h | N BASE/STRESS | Mean gross bp BASE/STRESS | Mean net bp BASE/STRESS | STRESS median / std bp | Equal-year STRESS bp | PF / win% | Max close+MTM DD% |',
        '|---|---:|---:|---:|---:|---:|---:|---:|---:|']
    for cid in ids:
        a,b=by[cid,'BASE'],by[cid,'STRESS']
        out.append(f"| {cid} | {b['horizon_hours']} | {a['trades']}/{b['trades']} | {f(a['mean_gross_bps'])}/{f(b['mean_gross_bps'])} | {f(a['mean_net_bps'])}/{f(b['mean_net_bps'])} | {f(b['median_net_bps'])}/{f(b['std_net_bps'])} | {f(b['equal_year_mean_net_bps'])} | {f(b['profit_factor'])}/{f(None if b['win_rate'] is None else b['win_rate']*100)} | {f(b['max_close_and_MTM_DD_pct'])} |")
    out+=['', '## Year split: selected four months only', '',
        'Equal-year net averages the represented years, while zero-trade years remain NA and are not invented zero trades. The fixed support gate still requires>=2years/6months for development and bothyears/4months for validation. Each year below includes all four admitted sampled month books, including no trades.', '',
        '| Candidate | Year | N BASE/STRESS | Mean net bp BASE/STRESS | Mean monthly cash return% BASE/STRESS | Active STRESS months |',
        '|---|---:|---:|---:|---:|---:|']
    for cid in ids:
        a,b=by[cid,'BASE'],by[cid,'STRESS']
        for ya,yb in zip(a['years'],b['years'],strict=True):
            out.append(f"| {cid} | {yb['year']} | {ya['trades']}/{yb['trades']} | {f(ya['mean_net_bps'])}/{f(yb['mean_net_bps'])} | {f(ya['mean_independent_month_account_return_pct'])}/{f(yb['mean_independent_month_account_return_pct'])} | {yb['represented_months']} |")
    out+=['', '## Monthly and side splits, including zero trades', '',
        'All granular side/month means, win rates,PF,R,min/q25/median/q75/max durations, active minutes, daily PnL/exposure, turnover, native proxy fees, stops/gaps,MAE/MFE and event-fate counts are in the stage result JSON. Zero-trade rows have undefined trade statistics, not manufactured economic rejection.', '']
    for cid in ids:
        a,b=by[cid,'BASE'],by[cid,'STRESS']
        out += [f'### {cid}', '',
            '| Month | N BASE/STRESS | Mean net bp BASE/STRESS | Median STRESS bp | STRESS win% / PF | STRESS R | Account return% BASE/STRESS | Close/dense DD% STRESS | Active% STRESS | LONG% STRESS | Duration median min |',
            '|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|']
        for x,y in zip(a['folds'],b['folds'],strict=True):
            out.append(f"| {y['fold']} | {x['trades']}/{y['trades']} | {f(x['mean_net_bps'])}/{f(y['mean_net_bps'])} | {f(y['median_net_bps'])} | {f(None if y['win_rate'] is None else y['win_rate']*100)}/{f(y['profit_factor'])} | {f(y['mean_net_R'])} | {f(x['account_return_pct'])}/{f(y['account_return_pct'])} | {f(y['trade_close_drawdown_pct'])}/{f(y['dense_trade_price_MTM_drawdown_pct'])} | {f(y['active_minutes_pct'])} | {f(None if y['long_share'] is None else y['long_share']*100)} | {f(None if y['duration_minutes_quantiles'] is None else y['duration_minutes_quantiles']['median'])} |")
        out+=['', '| STRESS side | N | Gross bp | Net mean/median bp | win% | PF | meanR |',
            '|---|---:|---:|---:|---:|---:|---:|']
        for side,x in b['sides'].items():
            out.append(f"| {side} | {x['trades']} | {f(x['mean_gross_bps'])} | {f(x['mean_net_bps'])}/{f(x['median_net_bps'])} | {f(None if x['win_rate'] is None else x['win_rate']*100)} | {f(x['profit_factor'])} | {f(x['mean_net_R'])} |")
        out+=['', '**Frozen gate failures:** '+', '.join(b['gate_failures'])+'.','']
    out+=['## No-signal comparison and fixed uncertainty', '',
        'PAUSE has zero exposure/orders/fees/USDTyield. Balanced control averages unfunded LONG/SHORT episodes at SAME parent timestamp, raw stop-distance, quantity,horizon,cost; both use the parent raw entry-notional denominator. Episodes may overlap and do not use parentDD/capital, so this is a paired entry-time comparison, not a profitable control portfolio or randomized causality test. A positive increment over a losing benchmark cannot rescue negative absolute net.', '',
        'Week-block10,000resamples, seed17022025; sampled UTC Monday calendar blocks within year, keeping no-trade eligible weeks, equal represented-year means. Missing/tradeless years are NA. Shared calendar draws across candidates support dependence accounting; fixed14d-from-score-start sensitivity is also published. Max24h tails can cross a week and prior concept/April-year exposure prevent pristine OOS claims. Six development families and at mosttwo preselected validation hypotheses receive .05/6 and .05/2 one-sided corrections. Two-side95% intervals and paired increment are disclosed; no IID tradeSE or permutation-randomization claim is made. Undefined sampled-year mass is conservatively -infinity for lower bounds; null is unbounded/undefined, never zero.', '',
        '| STRESS candidate | Equal-year absolute / paired increment bp | Net95% CI | Corrected one-sided net/increment LCB bp | Undefined week draws% |14d net95% CI |',
        '|---|---:|---|---:|---:|---|']
    for cid in ids:
        s=by[cid,'STRESS'];a=s['weekly_uncertainty'];b=s['fortnight_uncertainty']
        out.append(f"| {cid} | {f(s['equal_year_mean_net_bps'])}/{f(s['equal_year_mean_incremental_bps'])} | {a['net_ci95']} | {f(a['one_sided_net_LCB_bps'])}/{f(a['one_sided_increment_LCB_bps'])} | {f(a.get('undefined_sample_fraction',0)*100)} | {b['net_ci95']} |")
    out+=['', 'Development promotion does NOT require a positive interval lower bound: it literally requires>=50STRESStrades,>=2representedyears,>=6distinctscoredmonths,positiveequal-yearmean,>=2nonnegativeyearmeans,PF>1,maxbookclose+MTMDD<=15%,positiveequal-yearpairedincrement. Passing candidates rank fixed min(equal-yeartrade netbp,mean-monthcashreturnbp)/max(1,DDpct), then unique events, then lexicalID; max2. Nobody may relax support to promote the two-trade positive.', '',
        'Validation would require>=30trades,bothyears,>=4months,positiveequal-yearnet,onepositiveyear,neitheryear<-10bp,PF>=1.05,DD<=15%,pairedincrement>0. Its95%lower<=0 would mean UNCERTAIN_EXPLORATORY, not Alpha. On this development no-go, these future measurements are NOT_RUN, not zeros and not a validation failure.', '',
        '## Adverse Funding and opportunity limitations', '',
        'No signed Funding history or true Mark was acquired. Extra4/8bp debits are arithmetic scenarios per possible UTC8h settlement±15s and broad unknown-hourly cadence; full original quantity and touched-minute highs are conservative, and do not feed past entry decisions. No fabricated funding credits or guessed backfilled rates. They do not rerun cash/margin/liquidation after debits. At4/8/12/24h, endpoint-inclusive worst window counts are respectively1/2/2/4 for UTC8h and5/9/13/25 for hourly; unknowncadence is not silently8h.', '',
        '| STRESS candidate | Original net mean bp | UTC8h adverse4/8bp net mean | Hourly adverse4/8bp net mean | Gap stop losses / beyond-stop gross gap losses |',
        '|---|---:|---:|---:|---:|']
    for cid in ids:
        s=by[cid,'STRESS'];a=s['funding_sensitivity']['UTC8H_ASSUMED_SCHEDULE'];b=s['funding_sensitivity']['UNKNOWN_HOURLY_STRESS']
        out.append(f"| {cid} | {f(s['mean_net_bps'])} | {f(a['adverse4bp_mean_net_bps'])}/{f(a['adverse8bp_mean_net_bps'])} | {f(b['adverse4bp_mean_net_bps'])}/{f(b['adverse8bp_mean_net_bps'])} | {s['stop_gap_losses']}/{s['loss_beyond_raw_stop_bps']} |")
    out+=['', 'The strongest supported rejection is low-ER range reentry: sufficient trades and all years/months, negative gross and negative stress mean/interval. Flow-confirmed trend has positive2021 stress mean but negative2022/2023 and inadequate50-trade total; positive paired increment is not an absolute profitable strategy. Compression has a tiny positiveBASE mean but failsSTRESS and coverage. Absorption is a two-trade positive, not a credible promoted setup. Sustained24h now actually triggers, but fourtrade support is inadequate; none of these low-support rows prove universal absence of an edge.', '',
        'Feature diagnostics count actual completed15m windows, common warmup/volatility WAIT, first-after-hour eligibility and per-family emitted/fully-evaluated-not-met slots. They describe conjunction selectivity without inventing which unobserved economic cause was responsible. All generated signal fates, overlaps,rawrisk/gap rejection,ACKedgepurges and zero-trade months are retained; no source gap or rejected event silently becomes a winning fill.', '',
        '## Reproduction, tests and terminal decision', '',
        f"Measured {result['observations']} candidate/cost trade observations (cost replays are dependent), {len(ids)}variants×2costs×{len(result['full_folds'])}folds. Complete private event/trade/dense1m equity/exposure ledgers have SHA256/size entries in results. Trade ledger `{next(p['sha256'] for p in result['ledger_manifest'] if p['name']=='trade_ledger.jsonl')}`. A second identical frozen-stage run is compared bytewise including all ledger hashes; local focused test/compile/Ruff outputs and crosschecks are recorded in EXECUTION_RECEIPT.json. Three actual episodes receive independent Decimal fee/price/first-hit walkthrough via the unmodified R1 audit helper, not a whole-engine certification.", '',
        'The originalR1 code/tests/results, Controller files, CI/H40 and S3A remain unchanged. R2 adds only its four allowed namespaces; raw data and full price/trade paths are not tracked. Source/code review removed a parser rounding-tolerance path to honor the frozen strictB<=V rule (all actual downloaded observations already had zero excursions), and corrected shared calendar RNG consumption across missing candidate-years; this changes no strategy, gate, period, seed or fitted constant. Final run pairs use these exact frozen semantics. Full repository CI is not repeatedly run or waited on; the final exactSHA status is honestly reported externally after push, with no green claim or H40 waiver. R1 run38071163242 was already failed on the unmodified H40 graph hash (Controller records2837PASS/1FAIL/2SKIP); that is not repaired by this task.', '',
        'On DEVELOPMENT_NO_GO: publish development results and empty promotion in commit2, verify its remoteSHA, stop with no third commit and no reserved2024–2025new-month access. No setup cards, no extra parameters or windows. Any next strategy campaign requires separately frozen Controller authority; P2sourceadmission,P3effectiveprereg,P4/Alpha/testnet/live/real funds remainNONE.', '',
        'Derived artifacts: Binance Vision attribution; CC BY-NC-SA4.0; noncommercial nonproduction research.', '']
    (ROOT/'docs/strategy_research/g2_r3/flow_regime_r2'/f'BTC_FLOW_REGIME_{stage}_REPORT.md').write_text('\n'.join(out))


if __name__=='__main__':main()
