"""Independent P2 S3A single-file POSIX dir_fd Parquet footer reader package.

This package is 100% standalone and does not import from S1 or S2 modules.
It operates exclusively on synthetic temporary fixtures in S3A and rejects
any reference to the physical owner WSL data root fail-closed.
"""

from __future__ import annotations

from scripts.strategy_research.p2_s3_footer_reader.constants import (
    CODE_START_SHA,
    CONTROLLER_DISPATCH_SHA,
    CONTROLLER_S2_JOINT_DECISION_SHA,
    ETH_SOL_1M_PERP_STATUS,
    HEADER_STATUS_NOT_VERIFIED,
    IMMUTABLE_OWNER_DATA_ROOT,
    MAX_ATTEMPTED_FS_CALLS,
    MAX_FOOTER_READ_BYTES,
    MAX_TOTAL_FILE_READ_BYTES,
    MAX_TRAILER_READ_BYTES,
    ORIGINAL_STAT_RECEIPT_SHA,
    PROMPT_SHA,
    S3_SINGLE_PILOT_COMPONENTS,
    S3_SINGLE_PILOT_EXPECTED_SIZE_BYTES,
    S3_SINGLE_PILOT_REL_PATH,
    S3A_TERMINAL_STATUS,
    TASK_ID,
    VERIFIED_C6823DBC_FILE_SIZES_BYTES,
)
from scripts.strategy_research.p2_s3_footer_reader.errors import (
    ByteBudgetExceededError,
    CliOrEnvRootOverrideForbiddenError,
    CorruptedParquetFooterError,
    EACCESPermissionError,
    ENOENTNotFoundError,
    GrantAuthorizationError,
    GrantExpiredError,
    GrantScopeEscalationError,
    HardlinkOrAliasError,
    InvalidParquetFooterExtentError,
    InvalidParquetFooterLengthError,
    InvalidParquetFormatError,
    InvalidParquetMagicError,
    InvalidReadOffsetOrLengthError,
    MountBoundaryEscapeError,
    NonRegularFileError,
    NotADirectoryComponentError,
    ParserInputViolationError,
    PathSyntaxOrTraversalError,
    ProductionExecutionForbiddenError,
    ProtectedPathDeniedError,
    RowGroupDataReadForbiddenError,
    S3FooterReaderError,
    ShortReadOrTruncatedFileError,
    SymlinkDetectedError,
    SyscallBudgetExceededError,
    TOCTOUOrFDIdentityError,
    UnapprovedTargetFileError,
    UnsupportedPlatformError,
)
from scripts.strategy_research.p2_s3_footer_reader.fd_syscall_wrapper import (
    MeteredPosixSyscallWrapper,
    assert_not_owner_data_root,
    verify_posix_fd_platform_support,
)
from scripts.strategy_research.p2_s3_footer_reader.footer_parser import (
    parse_in_memory_parquet_footer,
    validate_parquet_trailer_and_extent,
)
from scripts.strategy_research.p2_s3_footer_reader.oracle_runner import (
    run_all_s3a_security_oracle_scenarios,
)
from scripts.strategy_research.p2_s3_footer_reader.reader import (
    SingleFileParquetFooterReader,
    validate_and_split_single_pilot_rel_path,
    validate_no_cli_or_env_overrides,
    validate_synthetic_grant,
)
from scripts.strategy_research.p2_s3_footer_reader.synthetic_fixtures import (
    build_synthetic_parquet_bytes,
    craft_custom_trailer_parquet_bytes,
    materialize_synthetic_pilot_tree,
)
from scripts.strategy_research.p2_s3_footer_reader.types import (
    ColumnSchemaSummary,
    FooterReadExecutionReceipt,
    SanitizedParquetFooterMetadata,
    SyntheticTestGrant,
    SyscallAccountingSnapshot,
    create_valid_synthetic_grant,
)

__all__ = [
    "CODE_START_SHA",
    "CONTROLLER_DISPATCH_SHA",
    "CONTROLLER_S2_JOINT_DECISION_SHA",
    "ETH_SOL_1M_PERP_STATUS",
    "HEADER_STATUS_NOT_VERIFIED",
    "IMMUTABLE_OWNER_DATA_ROOT",
    "MAX_ATTEMPTED_FS_CALLS",
    "MAX_FOOTER_READ_BYTES",
    "MAX_TOTAL_FILE_READ_BYTES",
    "MAX_TRAILER_READ_BYTES",
    "ORIGINAL_STAT_RECEIPT_SHA",
    "PROMPT_SHA",
    "S3A_TERMINAL_STATUS",
    "S3_SINGLE_PILOT_COMPONENTS",
    "S3_SINGLE_PILOT_EXPECTED_SIZE_BYTES",
    "S3_SINGLE_PILOT_REL_PATH",
    "TASK_ID",
    "VERIFIED_C6823DBC_FILE_SIZES_BYTES",
    "ByteBudgetExceededError",
    "CliOrEnvRootOverrideForbiddenError",
    "ColumnSchemaSummary",
    "CorruptedParquetFooterError",
    "EACCESPermissionError",
    "ENOENTNotFoundError",
    "FooterReadExecutionReceipt",
    "GrantAuthorizationError",
    "GrantExpiredError",
    "GrantScopeEscalationError",
    "HardlinkOrAliasError",
    "InvalidParquetFooterExtentError",
    "InvalidParquetFooterLengthError",
    "InvalidParquetFormatError",
    "InvalidParquetMagicError",
    "InvalidReadOffsetOrLengthError",
    "MeteredPosixSyscallWrapper",
    "MountBoundaryEscapeError",
    "NonRegularFileError",
    "NotADirectoryComponentError",
    "ParserInputViolationError",
    "PathSyntaxOrTraversalError",
    "ProductionExecutionForbiddenError",
    "ProtectedPathDeniedError",
    "RowGroupDataReadForbiddenError",
    "S3FooterReaderError",
    "SanitizedParquetFooterMetadata",
    "ShortReadOrTruncatedFileError",
    "SingleFileParquetFooterReader",
    "SymlinkDetectedError",
    "SyntheticTestGrant",
    "SyscallAccountingSnapshot",
    "SyscallBudgetExceededError",
    "TOCTOUOrFDIdentityError",
    "UnapprovedTargetFileError",
    "UnsupportedPlatformError",
    "assert_not_owner_data_root",
    "build_synthetic_parquet_bytes",
    "craft_custom_trailer_parquet_bytes",
    "create_valid_synthetic_grant",
    "materialize_synthetic_pilot_tree",
    "parse_in_memory_parquet_footer",
    "run_all_s3a_security_oracle_scenarios",
    "validate_and_split_single_pilot_rel_path",
    "validate_no_cli_or_env_overrides",
    "validate_parquet_trailer_and_extent",
    "validate_synthetic_grant",
    "verify_posix_fd_platform_support",
]
