"""r3_alt_engine: Clean event-sourced alternative research replay micro-engine."""

from btc_quant_agent.strategy_research.r3_alt_engine import (
    clock,
    execution,
    frozen_primitives,
    journal,
    model,
    money,
    reducer,
    replay,
    signals,
)
from btc_quant_agent.strategy_research.r3_alt_engine.frozen_primitives import (
    CandidateRegistry,
    CostModel,
    get_default_registry,
)
from btc_quant_agent.strategy_research.r3_alt_engine.model import (
    Bar1h,
    Bar1m,
    Bar4h,
    CandidateDefinition,
    CandidateFamily,
    CompletedTrade,
    CostScenario,
    Direction,
    EngineState,
    Event,
    EventKind,
    ExitReason,
    Horizon,
    MarkBar1m,
    OwnerKey,
    OwnerLedger,
    OwnerPhase,
    Posting,
    Projection,
    ReplayConfig,
    ReplayReport,
    SymbolFilters,
)
from btc_quant_agent.strategy_research.r3_alt_engine.replay import (
    ReplayEngine,
    SyntheticDataset,
)

__all__ = [
    "Bar1h",
    "Bar1m",
    "Bar4h",
    "CandidateDefinition",
    "CandidateFamily",
    "CandidateRegistry",
    "CompletedTrade",
    "CostModel",
    "CostScenario",
    "Direction",
    "EngineState",
    "Event",
    "EventKind",
    "ExitReason",
    "Horizon",
    "MarkBar1m",
    "OwnerKey",
    "OwnerLedger",
    "OwnerPhase",
    "Posting",
    "Projection",
    "ReplayConfig",
    "ReplayEngine",
    "ReplayReport",
    "SymbolFilters",
    "SyntheticDataset",
    "clock",
    "execution",
    "frozen_primitives",
    "get_default_registry",
    "journal",
    "model",
    "money",
    "reducer",
    "replay",
    "signals",
]
